### ISSUE TITLE
Enum inside record doesn't work

### ISSUE THREAD

**Issue by forsberg** [kun-fang/avro-data-model#2]
Tried the following minimal example:

```python
from avro_models import avro_schema, AvroModelContainer

names = AvroModelContainer()

schema = {
    "type": "record",
    "name": "minimal",
    "namespace": "com.example",
    "fields": [
        {
            "name": "examplestring",
            "type": "string"
        },
        {
            "name": "enum1",
            "type": {
                "type": "enum",
                "symbols": ["TEST1", "TEST2"],
                "name": "TestEnum"
            }
        },
        {
            "name": "enum2",
            "type": "com.example.TestEnum"
        }
    ]
}

@avro_schema(names, schema_json=schema)
class MinimalExample(object):
    pass

me = MinimalExample({"examplestring":"Hello", "enum1": "TEST1", "enum2": "TEST2"})
print(me.examplestring)
print(me.enum1)
print(me.enum2)
```

Unfortunately, it doesn't work:

```
$ python minimal.py
Hello
Traceback (most recent call last):
  File "minimal.py", line 35, in <module>
    print(me.enum1)
  File "/Users/erfor/.virtualenvs/avro_models/lib/python3.7/site-packages/avro_models/models.py", line 60, in __getattr__
    return item_class(self._value[attr])
TypeError: 'NoneType' object is not callable
```

I also tried creating a union of the two schemas, with the Enum defined first, and the record defines second. This also failed.

I don't want to work with multiple schema files and objects because I need to submit it to the avro schema server which as far as I know only accepts one schema per topic. 

Is there some way of making this work? I guess I *could* handle it as separate schemas and concatenate them into a union schema before submitting to the schema server, but that's cumbersome, and as far as I know, the above exampel schema is valid so it should work with avro-data-model.

**Comment by kun-fang** [comment]
Thanks for reporting the issue. It is a bug. I've fixed it in the latest version.
